def user_data_dir(a1: str, a2: str = "") -> str: ...
def user_cache_dir(a1: str, a2: str = "") -> str: ...
def user_config_dir(a1: str, a2: str = "") -> str: ...
def user_log_dir(a1: str, a2: str = "") -> str: ...
